FROM openjdk:8
EXPOSE 8083

RUN mkdir /app
ADD target/MS-Specialite-0.0.1-SNAPSHOT.jar /app/specialite-img.jar
ADD upload-directory /app/upload-directory

# Set the working directory to /app
WORKDIR /app
ENTRYPOINT ["java", "-jar", "specialite-img.jar"]