version: "3.9"
services:
  universite:
    build: .\Universite
    image: "universite-img"
    container_name: universite
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/universite?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - eureka
      - mysql-db
  foyer:
    build: .\Foyer
    image: "foyer-img"
    container_name: foyer
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      
    restart: unless-stopped
    depends_on:
      - eureka
  restaurant:
    build: .\Foyer
    image: "restaurant-img"
    container_name: restaurant
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
  
    restart: unless-stopped
    depends_on:
      - eureka
  chambre:
    build: .\GestionChambre
    image: "chambre-img"
    container_name: chambre
    ports:
      - "8091:8091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
   
    restart: unless-stopped
    depends_on:
      - eureka
  club-node:
    build:
      context: .\MS_club
      dockerfile: dockerfile
    image: "club-img"
    container_name: "club"
    ports:
      - "3000:3000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    restart: unless-stopped
    depends_on:
      - eureka
      
  event:
    build: .\Event-MS
    image: "event-img"
    container_name: event
    ports:
      - "8087:8087"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/event?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - eureka
      - mysql-db
  specialite:
    build: .\MS_specialite
    image: "specialite-img"
    container_name: specialite
    ports:
      - "8083:8083"
    volumes:
      - ./MS_specialite/upload-directory:/app/upload-directory
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/MS-Specialite?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-s
    depends_on:
      - eureka
      - mysql-db
  news:
    build: .\Educal-news
    image: news
    container_name: news
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/educal_news?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - eureka
      - mysql-db
  
  eureka:
    build: .\EurekaD
    image: "eureka-img"
    container_name: "eureka"
    ports:
      - "8761:8761"
    hostname: discovery

  gateway:
    build: .\ApiGateway
    image: "gateway-img"
    container_name: "gateway"
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - spring.cloud.gateway.routes[0].id=universite
      - spring.cloud.gateway.routes[0].uri=http://localhost:8084
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/universite/**

      - spring.cloud.gateway.routes[1].id=specialite
      - spring.cloud.gateway.routes[1].uri=http://localhost:8083
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/specialites/**

      - spring.cloud.gateway.routes[2].id=foyer
      - spring.cloud.gateway.routes[2].uri=http://localhost:8081
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/Foyer/**

      - spring.cloud.gateway.routes[3].id=chambre
      - spring.cloud.gateway.routes[3].uri=http://localhost:8091
      - spring.cloud.gateway.routes[3].predicates[0]=Path=/** 

      - spring.cloud.gateway.routes[4].id=event
      - spring.cloud.gateway.routes[4].uri=http://localhost:8087
      - spring.cloud.gateway.routes[4].predicates[0]=Path=/event/**

      - spring.cloud.gateway.routes[5].id=restaurant
      - spring.cloud.gateway.routes[5].uri=http://localhost:8090
      - spring.cloud.gateway.routes[5].predicates[0]=Path=/restaurants/**

      - spring.cloud.gateway.routes[6].id=news
      - spring.cloud.gateway.routes[6].uri=http://localhost:8085
      - spring.cloud.gateway.routes[6].predicates[0]=Path=/news/**

      - spring.cloud.gateway.routes[7].id=club
      - spring.cloud.gateway.routes[7].uri=http://localhost:3000
      - spring.cloud.gateway.routes[7].predicates[0]=Path=/clubs/**
    depends_on:
      - universite
  mysql-db:
    # build: "mysql:5.6"
    image: "mysql:5.6"
    container_name: "mysql-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root #indisponsable pour la conteneurisation
      #- MYSQL_DATABASE=job
    ports:
      - "3306:3306"
    restart: unless-stopped
    # hostname: mysql-host ya host name ya nesta3mel container name

  
